### PR TITLE
Fix configuration loading

### LINKED ISSUE #380: Regressions raising after bumping elemental-cli in elemental-toolkit
Now elemental-cli returns error in various points while loading the configuration files. Previously several of these errors were swallowed causing a fallback to defaults. Now errors are caught and it causes failures were it shouldn't. The obvious case is with `elemental install` when no configuration file is present, now it fails. This can be seen at https://github.com/rancher/elemental-toolkit/actions/runs/3498251946/jobs/5858917572

### LINKED ISSUE #385: Duplicate "default" in help output for "install"
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Run
```
elemental install -h
```
outputs
```
...
Global Flags:
      --config-dir string   Set config dir (default is /etc/elemental) (default "/etc/elemental")
...
```

(note the duplication of "default")

**What did you expect to happen:**

```
...
Global Flags:
      --config-dir string   Set config dir (default is "/etc/elemental")
...
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Elemental-cli version 0.0.15+g605346d

- Elemental release version (use `cat /etc/os-release`):
- Rancher version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

### PR DESCRIPTION
**Pull request by davidcassany**
This commit ensures viper only tries to merge files that already exist.

In addition this commit properly sets default configuration directory for build commands.

Fixes #380

Signed-off-by: David Cassany <dcassany@suse.com>

### CODE REVIEW

File: cmd/config/config.go [hunk 1]
```diff
@@ -100,16 +100,19 @@ func bindGivenFlags(vp *viper.Viper, flagSet *pflag.FlagSet) {
...
 		config.WithMounter(mounter),
 	)
 
 	configLogger(cfg.Logger, cfg.Fs)
+	if configDir == "" {
+		configDir = "."
+		cfg.Logger.Info("reading configuration from current directory")
+	} else {
+		cfg.Logger.Info("reading configuration form '%s'", configDir)
+	}
```
Comment (davidcassany) [inline cmd/config/config.go:115]: Log the directory we are loading configuration from

File: cmd/config/config.go [hunk 2]
```diff
@@ -138,8 +141,11 @@ func ReadConfigRun(configDir string, flags *pflag.FlagSet, mounter mount.Interfa
 		config.WithLogger(v1.NewLogger()),
 		config.WithMounter(mounter),
 	)
-
 	configLogger(cfg.Logger, cfg.Fs)
+	if configDir == "" {
+		configDir = constants.ConfigDir
+	}
+	cfg.Logger.Info("reading configuration form '%s'", configDir)
```
Comment (davidcassany) [inline cmd/config/config.go:148]: Set here the configuration default directory, not at flags level, otherwise we can't distinguish between build and runtime commands.

File: cmd/config/config.go [hunk 3]
```diff
@@ -148,40 +154,40 @@ func ReadConfigRun(configDir string, flags *pflag.FlagSet, mounter mount.Interfa
 
 		err := viper.MergeInConfig()
 		if err != nil {
-			cfg.Logger.Warnf("error merging os-release file: %s", err)
+			cfg.Logger.Error("error merging os-release file: %s", err)
```
Comment (davidcassany) [inline cmd/config/config.go:157]: We return error, hence they should be error messages.

File: cmd/config/config.go [hunk 4]
```diff
@@ -148,40 +154,40 @@ func ReadConfigRun(configDir string, flags *pflag.FlagSet, mounter mount.Interfa
...
 			return cfg, err
 		}
 	}
 
 	// merge yaml config files on top of default runconfig
-	if exists, _ := utils.Exists(cfg.Fs, configDir); exists {
+	if exists, _ := utils.Exists(cfg.Fs, filepath.Join(configDir, "config.yaml")); exists {
```
Comment (davidcassany) [inline cmd/config/config.go:163]: Make sure we tests the actual file, not the directory

File: cmd/root.go [hunk 5]
```diff
@@ -30,7 +30,7 @@ func NewRootCmd() *cobra.Command {
 		Short: "Elemental",
 	}
 	cmd.PersistentFlags().Bool("debug", false, "Enable debug output")
-	cmd.PersistentFlags().String("config-dir", "/etc/elemental", "Set config dir (default is /etc/elemental)")
+	cmd.PersistentFlags().String("config-dir", "", "Set config dir")
```
Comment (davidcassany) [inline cmd/root.go:33]: This default was making the build configuration load to never look at the current directory. Better set the default on build config load and on run config load.

**Review by davidcassany — COMMENTED** [review]
@frelon See this PR is slightly different from what you did, the error fix is the same: test the actual file to load exists.

However in this PR I added few additional logging comments, a couple of tests for bad formatted yamls and fix the default configuration directory for build commands.

**Comment by frelon** [comment]
Very nice! I will close my PR in favor of this one! :+1:

**Review by frelon — APPROVED** [review]
LGTM!
