### PR TITLE
Set labels used by grub to find system disks

### LINKED ISSUE #632: Upgrading from Stable Elemental Teal to Dev Elemental Teal fails
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

The OS upgrade fails. Mostly because the upgrade hooks are applied with a wrong environment

**What did you expect to happen:**

A successful upgrade

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The issue is related with the suc-upgrade script and with its runtime environment.

**Environment:**

- Elemental release version (use `cat /etc/os-release`):
- Rancher version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:

### PR DESCRIPTION
**Pull request by frelon**
This commit sets GRUB persistent variables for filesystem labels after install/upgrade/reset. These labels are used in the new GRUB configuration when booting the system.

Signed-off-by: Fredrik Lönnegren <fredrik.lonnegren@suse.com>

### CODE REVIEW

File: pkg/action/install.go [hunk 1]
```diff
@@ -205,6 +206,22 @@ func (i InstallAction) Run() (err error) {
 		return elementalError.NewFromError(err, elementalError.HookAfterInstall)
 	}
 
+	err = grub.SetPersistentVariables(
+		filepath.Join(i.spec.Partitions.State.MountPoint, constants.GrubOEMEnv),
+		map[string]string{
+			"state_label":    i.spec.Partitions.State.FilesystemLabel,
+			"active_label":   i.spec.Active.Label,
+			"passive_label":  i.spec.Passive.Label,
+			"recovery_label": i.spec.Partitions.Recovery.FilesystemLabel,
```
Comment (davidcassany) [inline pkg/action/install.go]: Edited: ~I know this might be confusing, but this should be `i.spec.Recovery.Label`~ the comment is wrong, code was already fine, sorry 🙏🏽

File: pkg/action/install.go [hunk 2]
```diff
@@ -205,6 +206,22 @@ func (i InstallAction) Run() (err error) {
...
+			"system_label":   constants.SystemLabel,
```
Comment (davidcassany) [inline pkg/action/install.go]: Edited: ~Then this one should be `i.spec.Partitions.Recovery.FilesystemLabel`~ this is also a wrong comment, sorry 🙏🏽 It should have been `i.spec.Partitions.Recovery.Images[constants.RecoveryImgName].Label`

File: pkg/action/reset.go [hunk 3]
```diff
@@ -213,6 +213,22 @@ func (r ResetAction) Run() (err error) {
...
 	}
 
+	err = grub.SetPersistentVariables(
+		filepath.Join(r.spec.Partitions.State.MountPoint, cnst.GrubOEMEnv),
+		map[string]string{
+			"state_label":    r.spec.Partitions.State.FilesystemLabel,
+			"active_label":   r.spec.Active.Label,
+			"passive_label":  r.spec.Passive.Label,
+			"recovery_label": r.spec.Partitions.Recovery.FilesystemLabel,
+			"system_label":   cnst.SystemLabel,
```
Comment (davidcassany) [inline pkg/action/reset.go]: Here applies the same as in install. But here is tricky, because there is no such a `r.spec.Recovery`, however such a value can be computed form the install state. So something like `r.spec.State.Partitions[cnst.RecoveryPartName].FSLabel`

File: pkg/action/install.go [hunk 4]
```diff
@@ -205,6 +206,22 @@ func (i InstallAction) Run() (err error) {
...
+			"oem_label":      i.spec.Partitions.OEM.FilesystemLabel,
```
Comment (davidcassany) [inline pkg/action/install.go]: Persistent partition is missing here, should be added too. You have not really missed it, I noted this was also missing in the former hook.

File: pkg/action/upgrade.go [hunk 5]
```diff
@@ -237,6 +237,22 @@ func (u *UpgradeAction) Run() (err error) {
 		return elementalError.NewFromError(err, elementalError.HookAfterUpgrade)
 	}
 
+	err = utils.NewGrub(&u.config.Config).SetPersistentVariables(
```
Comment (davidcassany) [inline pkg/action/upgrade.go:241]: I have doubts about adding this as part of the upgrade... also has the upgrade spec all the values we need? We need to be careful here.

**Review by davidcassany — COMMENTED** [review]
Beyond some details regarding specific recovery label values (yes, having recovery partitions and recovery images both with labels make it confusing), I  think this is good :+1:

Something I have been wondering about is if we should create some sort of interface with common methods for `InstallSpec`, `UpgradeSpec`, `ResetSpec` so we could, for instance, create a method that returns the labels map and just make use of with the grub object.

Also I am wondering if the setting of these persistent labels should be part of the installation method of grub and also have it as a devoted method in grub object. My idea is that within the actions logic this should be transparent or nearly transparent and keep required bootloader steps in there as a single block.

I am think about all this as I'd like to refactor elemental-cli grub logic at mid term to make it more as a library as a `bootloader` package and include in there the logic for live ISO, install/upgrade/reset and build-disks. So the more contained we have the logic of grub the better I'd say.

File: pkg/action/upgrade.go (hunk 5 above)
Comment (frelon) [reply pkg/action/upgrade.go:241]: Hmm, good point! I did run the upgrade on a elemental-teal install and the labels were set, but I did not try changing them from the defaults.

File: pkg/action/install.go (hunk 4 above)
Comment (frelon) [reply pkg/action/install.go]: It felt like there was something missing! Will add that one as well!

File: pkg/action/upgrade.go (hunk 5 above)
Comment (davidcassany) [reply pkg/action/upgrade.go:241]: After a further thought I think this is fine running again the labels setting during the upgrade. Makes sense to keep it aligned. Only image labels are exchangeable during the upgrade, so updating the lables makes sense and I believe setting all labels together is just safer and simpler than trying to just apply the ones that actually change.

File: pkg/types/v1/config.go [hunk 6]
```diff
@@ -369,7 +369,7 @@ func NewElementalPartitionsFromList(pl PartitionList, state *InstallState) Eleme
 	ep.OEM = pl.GetByNameOrLabel(constants.OEMPartName, lm[constants.OEMPartName])
 	ep.Recovery = pl.GetByNameOrLabel(constants.RecoveryPartName, lm[constants.RecoveryPartName])
 	ep.State = pl.GetByNameOrLabel(constants.StatePartName, lm[constants.StatePartName])
-	ep.Persistent = pl.GetByNameOrLabel(constants.PersistentPartName, lm[constants.PersistentLabel])
+	ep.Persistent = pl.GetByNameOrLabel(constants.PersistentPartName, lm[constants.PersistentPartName])
```
Comment (davidcassany) [inline pkg/types/v1/config.go:372]: 😱 thanks!

File: pkg/action/install.go [hunk 7]
```diff
@@ -21,6 +21,7 @@ import (
 	"path/filepath"
 	"time"
 
+	"github.com/rancher/elemental-cli/pkg/constants"
```
Comment (davidcassany) [inline pkg/action/install.go]: Note the line below already adds constants. I am the one to blame here, I named them `cnst` to type less when I started coding elemental-cli in several places. That was before I started using VSCode and its automatic imports, back then I was using `Vim` as my single editor, so typing less was relevant 😅 

Feel free to use `cnst` or `constants` at your choice, but I'd stick to one in the same file.

File: pkg/types/v1/grub.go [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+limitations under the License.
+*/
+
+package v1
+
+import (
+	"github.com/rancher/elemental-cli/pkg/constants"
+)
+
+func (i InstallSpec) GetGrubLabels() map[string]string {
```
Comment (davidcassany) [inline pkg/types/v1/grub.go:23]: Yes, loving it, probably later on we can think on extending this file with further methods and create an interface for the methods, so we can imagine something like:

```golang
utils.NewGrub(&u.config.Config, spec)
```

so we could compute all those non obvious grub parameters as part of grub internals.

**Review by davidcassany — APPROVED** [review]
Awesome, looks good :+1:

File: pkg/action/install.go (hunk 7 above)
Comment (frelon) [reply pkg/action/install.go]: Oops, good catch! Yep, I will stick to the one used in the file!

File: pkg/types/v1/grub.go (hunk 8 above)
Comment (frelon) [reply pkg/types/v1/grub.go:23]: That's a great idea!

File: pkg/types/v1/config.go (hunk 6 above)
Comment (frelon) [reply pkg/types/v1/config.go:372]: Hehe, took some time before I realized why I got nil for the persistent partition everywhere :sweat_smile:

File: pkg/config/config.go [hunk 9]
```diff
@@ -274,7 +274,7 @@ func NewInstallElementalParitions() v1.ElementalPartitions {
 func getActivePassiveAndRecoveryState(state *v1.InstallState) (active, passive, recovery *v1.ImageState) {
 	recovery = &v1.ImageState{
 		FS:    constants.LinuxImgFs,
-		Label: constants.RecoveryLabel,
+		Label: constants.SystemLabel,
```
Comment (frelon) [inline pkg/config/config.go:277]: @davidcassany FYI, I'm pretty sure this is the correct label, but better with two pair of eyes.

Comment (davidcassany) [reply pkg/config/config.go:277]: Indeed... 🤦🏽 damn! how bad I did it...

**Comment by davidcassany** [comment]
@frelon I consider this ready to be merged. Thanks for the patience and for few unrelated fixed in the former code :+1:
